### ISSUE TITLE
I find a bug in ByteUtil.java

### ISSUE THREAD

**Issue by QDPeng** [EspressifApp/EsptouchForAndroid#10]
public static String parseBssid(byte[] bssidBytes, int offset, int count) {
		byte[] bytes = new byte[count];
		for (int i = 0; i < count; i++) {
			bytes[i] = bssidBytes[i + offset];
		}
		return parseBssid(bytes);
}
here may throw a outOfBound exception:
 bytes[i] = bssidBytes[i + offset];// i + offset may generate a big long value, sometimes

**Comment by XuXiangJun** [comment]
bssid length must be 6
exception is requirement
