### ISSUE TITLE
如何获取到设备接收到广播后的回复信息

### ISSUE THREAD

**Issue by unmagic** [EspressifApp/EsptouchForAndroid#12]
在App发送udp广播给设备后，设备会回复消息给App，SDK中有相关接口接收该回复消息吗？

**Comment by afunx** [comment]
https://github.com/EspressifApp/IOT-Espressif-Android
可能你需要看的是这个：https://github.com/EspressifApp/IOT-Espressif-Android/blob/master/java/BASE/com/espressif/iot/base/net/udp/UdpBroadcastUtil.java

**Comment by Faynman** [comment]
同问

**Comment by XuXiangJun** [comment]
EspTouch 只是用于设备配网的库
并不涉及后续的通信
