### ISSUE TITLE
EsptouchForAndroid -Jar包

### ISSUE THREAD

**Issue by zxg1351** [EspressifApp/EsptouchForAndroid#15]
我想问下，如何下载EsptouchForAndroid这个最新的jar包。我现在想需要使用最新的Esptouch.jar。是需要我们自己来进行封装jar包么？

**Comment by afunx** [comment]
https://github.com/EspressifApp/IOT-Espressif-Android/tree/master/libs

libEsptouch_v0.3.4.5.jar

**Comment by EspressifApp** [comment]
如果使用的是AndroidStudio开发，直接把esptouch模块导入就可以了
如果一定需要jar包，已经提交到了根目录libs文件夹下
@zxg1351
