### ISSUE TITLE
麻烦告诉一下AES_SECRET_KEY这个key是什么

### ISSUE THREAD

**Issue by imangohome** [EspressifApp/EsptouchForAndroid#20]
![default](https://user-images.githubusercontent.com/36958122/43307116-f045b566-91af-11e8-8375-2261b45c5971.png)

**Comment by XuXiangJun** [comment]
这个需要与 Device 端约定
App 会对数据用这个 Key 进行 AES-128 加密， 设备端需要使用此 Key 进行解密
如果 Device 端没有进行解密处理的话，EspAES 参数只能传 null， 要不然 Device 无法识别加密数据

**Comment by imangohome** [comment]
@XuXiangJun 就是说有两种方式，一是和设备约定，可以传随意字符串，设备端自己解密，二是传一个null，设备端不用解密是吗

**Comment by XuXiangJun** [comment]
并不是随便传的， AES-128 的 Key 是长度为 16 的 byte[]
需要使用 AES 加密的话可能需要 Device 端的开发能力
