### ISSUE TITLE
怎么控制配网设备的数量

### ISSUE THREAD

**Issue by imangohome** [EspressifApp/EsptouchForAndroid#21]
想请问一下，怎么可以每次智能配网只配一个设备啊，比如附近有两个等待智能配网的设备，但是我只需要配一个

**Comment by XuXiangJun** [comment]
如果两个设备都开启了 Esptouch 模式，是没有办法只配一个的
因为路由器往空气中发包的时候，只要开启了 Esptouch 模式的设备都能抓到相关的数据包
