### ISSUE TITLE
Error in Xamarin Crossplatform

### ISSUE THREAD

**Issue by frankygoop** [EspressifApp/EsptouchForAndroid#22]
Hello, Maybe this is not the right place for this issue but I have tried several ways to make this work in xamarin forms for crossplatforms but always get error "missing partial modifier" in the EsptouchTask module.
If anyone knows how should be done please advise.
I am desperate to use this great library. 
thanks

**Comment by felizalde** [comment]
I was getting the same error than you. Here my solution:

1- First you need follow these steps: (I think you already are doing this) 
https://developer.xamarin.com/guides/android/advanced_topics/binding-a-java-library/binding-a-jar/

2- Add this into Metadata.xml. (Metada.xml is below Transforms folder.)
```
<metadata>

<remove-node path="/api/package[@name='com.espressif.iot.esptouch']/interface[@name='IEsptouchTask']" />

</metadata>
```

3- Add the .DLL file created into your Xamarin project. All should works.

I don't know if you know, but also there is [this ](https://github.com/lucafabbri/EspTouchBinding-Xamarin-iOS-Droid) project with the Esptouch Binding already created, but it not use the last version of EsptouchForAndroid.
