### ISSUE TITLE
您好，我想问下，这个配网成功后，如何实现APP与机器的绑定操作？

### ISSUE THREAD

**Issue by EalenLuo** [EspressifApp/EsptouchForAndroid#26]

**Comment by EspressifApp** [comment]
EspTouch 只是用于配网功能的

**Comment by EalenLuo** [comment]
好的，感谢回答！

**Comment by EalenLuo** [comment]
另外，我想问一下：利用APP给机器配网，一般需要多久，

**Comment by EalenLuo** [comment]
另外，我想问一下  
1、利用APP给机器配网，一般需要多久  
2、该demo最新版本无法配合esp32使用配网功能，目前esp32的SmartConfig有两个版本：V2.6.8 & V2.7.1  
3、但是这个demo是可以的https://github.com/EspressifApp/IOT-Espressif-Android-APK

**Comment by Faynman** [comment]
配网成功后如何获取设备的IP和端口号？还有就是已配网成功后，再次配网会失败。

**Comment by XuXiangJun** [comment]
@Faynman 
接口 IEsptouchListener 的回调方法 void onEsptouchResultAdded(IEsptouchResult result);
调用 result 的方法 InetAddress getInetAddress(); 可以获得设备的 IP 地址

调用 EsptouchTask 的 setEsptouchListener 设置回调接口

**Comment by Faynman** [comment]
@XuXiangJun 谢谢，我测试看看
