### ISSUE TITLE
can i send custom data like id to esp32 by esptouch?

### ISSUE THREAD

**Issue by dimasoktanugraha** [EspressifApp/EsptouchForAndroid#28]
i have many device which has unique id. before i want to use smartconfig, i want to check the device's id and just execute smartconfig which has same id that i sent before. can i do this?

**Comment by EspressifApp** [comment]
Sorry, current EspTouch protocol doesn't support this feature.

**Comment by dimasoktanugraha** [comment]
So, i can't send other data on esptouch?

**Comment by EspressifApp** [comment]
Custom data is not supported on EspTouch.

**Comment by dimasoktanugraha** [comment]
even though i change all code in this android project, is it still impossible to send the custom data to esp32? or esp32 cant read the custom data?

**Comment by EspressifApp** [comment]
If you modify android code, the IDF smart config code also needs to be modified, otherwise Esp32 device cannot recognize the custom data

**Comment by dimasoktanugraha** [comment]
so, how to modify IDF smart config? i cant find smart config's detail code on esp32's library

**Comment by XuXiangJun** [comment]
Now smart config v2 support 64 bytes custom data
