### ISSUE TITLE
Android 9 (SDK API LEVEL 28) Error, It doesn't shows SSID and BSSID.

### ISSUE THREAD

**Issue by MrityunjaiKumar** [EspressifApp/EsptouchForAndroid#31]
Even though connected to WIFI 2.4GHz access point, the Android pie doesn't show any ssid and bssid. Although same code works in lower API.

![image](https://user-images.githubusercontent.com/6240777/53649899-4944f780-3c69-11e9-8572-e8b72d259311.png)

**Comment by XuXiangJun** [comment]
GPS is required to be turned on on Android 9

**Comment by akatsuki821** [comment]
One of our tester using Android 9.0. He turned on the GPS but keep getting the "Configure fail" error, while the same code worked well on Android 7.0 and 8.1

**Comment by chander-60905** [comment]
WifiManager.EXTRA_WIFI_INFO is deprecated in sdk 28 version.
