### ISSUE TITLE
Not working for Huawei EMUI9.0

### ISSUE THREAD

**Issue by liaoweiguo** [EspressifApp/EsptouchForAndroid#32]
app can obtain SSID, but config failed after a while

**Comment by atmocom** [comment]
Similar issue here, in my case, SSID unknown and smart config fails. (Huawei/Honor 10, EMUI9.0)

**Comment by XuXiangJun** [comment]
@atmocom Have you granted the permission and turned on Location?
I have tested on Huawei Mate9(EMUI 9.0) and P30(EMUI 9.1), and both work well.

**Comment by atmocom** [comment]
I removed and reinstalled and then it started to work. Probably some issue with phone cloning from previous Motorola G5 that messed up something.
