### ISSUE TITLE
Working but going into onFailed 

### ISSUE THREAD

**Issue by omkar1707** [EspressifApp/EsptouchForAndroid#39]
I have debugged the app. And here are the observations.

`List<IEsptouchResult> result` is returning 1 device but `firstResult.isSuc()` is false.
And after that, the device is operated very well from MQTT Dash app.

What can be wrong here? Can you provide some more info on this?

**Comment by XuXiangJun** [comment]
The timeout of EsptouchTask is one minute.
Maybe the device has got the SSID and password, but connect the AP more than one minute.
