### ISSUE TITLE
双频路由器，没有2.4G设备连接路由器时，无法配网，双频设备自动切换为5G信号

### ISSUE THREAD

**Issue by ChowenPan** [EspressifApp/EsptouchForAndroid#42]
双频路由器，没有2.4G设备连接路由器时，无法配网，双频设备自动切换为5G信号

**Comment by XuXiangJun** [comment]
esp32和esp8266都不支持5G信号的
手机只能在2.4G下才能保证配网成功

**Comment by XuXiangJun** [comment]
那你可以尝试下发组播包看能不能配上

**Comment by ChowenPan** [comment]
这个问题无解？

**Comment by XuXiangJun** [comment]
> 

确实无解
设备硬件层不支持 5G 频段
APP 这边无能为力啊
如果只是为了配网的话可以使用 BluFi 或者 idf-provision
