### ISSUE TITLE
请问可以手机开启自身热点后给设备配网吗?

### ISSUE THREAD

**Issue by Yubyf** [EspressifApp/EsptouchForAndroid#43]
当前无第三方路由情况下, 想使用本机为设备配网, 在使用本项目 Demo 与本方法时设备没反应

**Comment by XuXiangJun** [comment]
这个是不行的
至少需要一台热点和另一台用于配网的手机

**Comment by Yubyf** [comment]
> 这个是不行的
> 至少需要一台热点和另一台用于配网的手机

好的，谢谢
