### ISSUE TITLE
如何在新版安卓版本下，正确显示ssid而不是unknown ssid?

### ISSUE THREAD

**Issue by wxiangcheng** [EspressifApp/EsptouchForAndroid#44]
旧版本的安卓手机可以用，换成新版本的手机，老是显示unknown ssid, 设置什么位置，定位权限之类的，也没搞定。这意思就是新版本手机，以后不能用这个espTouch了吗？smartconfig这个功能还能用吗？

**Comment by XuXiangJun** [comment]
请问是使用最新的代码吗？
手机的系统版本是Android 10？
最新的版本已经对Android 10做过兼容处理了

**Comment by wxiangcheng** [comment]
> 感谢回复。最新版本是指esptouch.apk version 1.1.0吗？安卓9.x 支持吗？
> 
> 请问是使用最新的代码吗？
> 手机的系统版本是Android 10？
> 最新的版本已经对Android 10做过兼容处理了

**Comment by wxiangcheng** [comment]
好的。刚试了下，这个1.10 在安卓10上可以。我再试下其它版本。
Thanks
