### ISSUE TITLE
esptouchforandroid release版本v1.1.0下载不了

### ISSUE THREAD

**Issue by enric-lee** [EspressifApp/EsptouchForAndroid#46]
点击esptouchforandroid release V1.1.0的下载按钮，无法下载。
[https://github.com/EspressifApp/EsptouchForAndroid/tags](url)

**Comment by XuXiangJun** [comment]
https://github.com/EspressifApp/EsptouchForAndroid/releases/download/v1.1.0/esptouch.apk
这个地址下不了？

**Comment by XuXiangJun** [comment]
代码
https://github.com/EspressifApp/EsptouchForAndroid/archive/v1.1.0.zip
