### ISSUE TITLE
请问为什么存在两个版本号？

### ISSUE THREAD

**Issue by zhongwcool** [EspressifApp/EsptouchForAndroid#5]
比如master中是v0.3.4.5，而tag中出现了v0.3.5.3，看起来都是主版本号，应该如何分辨呢？

**Comment by EspressifApp** [comment]
可否发送一个你的下载链接。我使用[https://github.com/EspressifApp/EsptouchForAndroid.git](https://github.com/EspressifApp/EsptouchForAndroid.git)，未发现你所说的问题。

**Comment by zhongwcool** [comment]
我使用的是相同的链接，不过选择了tag v0.3.5.3: https://github.com/EspressifApp/EsptouchForAndroid/tree/v0.3.5.3 
实际上tag中最新版本已经到v0.3.5.3，但代码中的版本号仍然是v0.3.4.6？

**Comment by afunx** [comment]
抱歉，应该是res中忘记改了。请尽量使用最新版本的。在新版本中，Android log中也会打版本号了。类似于这样的log："Welcome Esptouch v0.3.4.6"。

**Comment by zhongwcool** [comment]
谢谢。所以最新的版本号其实应该已经是v0.3.5.3?

**Comment by afunx** [comment]
嗯。是的。

**Comment by zhongwcool** [comment]
好的，明白，感谢。
另外提醒一下，目前的master主分支的代码并不是最新的（在没有分支的情况下，主分支是旧代码，而tag代码居然比较新？）。

**Comment by afunx** [comment]
谢谢。下次发布的时候，会纠正这个错误的。

**Comment by afunx** [comment]
这个tag是搞错了，有次push ios esptouch时，搞错了。我马上就把它弄好。最新的android esptouch是v0.3.4.6。

**Comment by afunx** [comment]
我已经改完啦。感觉应该没问题了。你可以再重新下载一份看看。

**Comment by zhongwcool** [comment]
好的 除了AndroidManifest.xml，其他应该都改好了。
