### ISSUE TITLE
BSSID not sent to ESP device

### ISSUE THREAD

**Issue by j1and1** [EspressifApp/EsptouchForAndroid#50]
I used the smart config sample code located on esp-idf repo I just added 2 lines to log out BSSID and BSSID_set property and BSSID is not set and the value is always 0.

As I'm using hidden WiFi network the BSSID field is required to connect to it, but as it is always empty on the other end I can't use smart config.

**Comment by XuXiangJun** [comment]
What version of esp-idf are you using?

**Comment by j1and1** [comment]
@XuXiangJun the esp-idf vtersion is `ESP-IDF v4.1-dev-1572-g30372f5a4` runing on linux mint.... 

I tried to dump out the received `smartconfig_event_got_ssid_pswd_t` so I can see the data... theres only password and `SSID` set in memory and the other fields are just zeroed out...

**Comment by XuXiangJun** [comment]
App will always send bssid data, but I don't know how device receive the data.
Maybe you can commit this issue in project [esp-idf](https://github.com/espressif/esp-idf)

**Comment by j1and1** [comment]
Thanks for the info will do so. Closing for now.
