### ISSUE TITLE
ssid无法输入

### ISSUE THREAD

**Issue by MasterLivens** [EspressifApp/EsptouchForAndroid#51]
如题，在界面上ssid一直为灰色，焦点在密码输入框里头。

**Comment by XuXiangJun** [comment]
EspTouch 必需连接 Wi-Fi 才能正常工作
Demo APP 会获取当前连接的 Wi-Fi 信息，包括 SSID 和 BSSID
如果一定需要自定义 SSID 的话，自己把 SSID 的 TextView 改成 EditText 就行了
