### ISSUE TITLE
普遍配网慢，Android9上经常收不到配网反馈，Android10配网失败

### ISSUE THREAD

**Issue by Tingdang** [EspressifApp/EsptouchForAndroid#59]
对同一个硬件，用同一个安卓手机，用官方demo测试，普遍配网比iOS慢，Android9上经常收不到配网反馈，Android10固定配网失败。但是：
换成涂鸦的app进行上述测试，没有问题，配网在5秒以内完成（我们的最快是9秒）。搞不懂涂鸦做了些什么改动，为什么这么快，这么稳定，连Android10都没有问题。

**Comment by Tingdang** [comment]
今天跟踪了好久，终于找到原因了并解决问题了。请大家检查一下__EsptouchTask文件中的__execute函数执行流程，我是把这个函数重写了后解决问题的。

**Comment by zhubinsheng** [comment]
> 今天跟踪了好久，终于找到原因了并解决问题了。请大家检查一下__EsptouchTask文件中的__execute函数执行流程，我是把这个函数重写了后解决问题的。

大神 是否可以帖一下代码学习一下 膜拜中

**Comment by zhubinsheng** [comment]
> 今天跟踪了好久，终于找到原因了并解决问题了。请大家检查一下__EsptouchTask文件中的__execute函数执行流程，我是把这个函数重写了后解决问题的。

__execute的工作流程看了，不知道怎么修改，跪求大神赐教

**Comment by XuXiangJun** [comment]
> 今天跟踪了好久，终于找到原因了并解决问题了。请大家检查一下__EsptouchTask文件中的__execute函数执行流程，我是把这个函数重写了后解决问题的。

能不能分享下怎么修改的 OTL

**Comment by philong9192** [comment]
@Tingdang How to change "__execute" function in "__EsptouchTask" class. I have the same problem on android 9 and 10, android below working fine, please help me.

**Comment by philong9192** [comment]
@XuXiangJun Please tell me, how to fix this bug? I can't config esp using android 9 and 10.

**Comment by Tingdang** [comment]
抱歉，这段时间没有上gtihub,没有看到。因为修改是在公司的项目中进行的，不方便贴源代码。我只能给出修改思路。对比iPhone，我跟踪Android APP发现两个问题:1.guide code和data code经常没有完整发送完，这个有很大概率会导致发送配网数据失败，修改__execute函数主要是解决这个问题；2.在__listenAsyn函数里，超时收到反馈时，是忽略结果的，这个要改掉，Android手机的硬件差异导致，很多手机上必然会存在接收超时。另外，mWaitUdpReceivingMilliseond和mWaitUdpSendingMillisecond我都调小了，设置那么长时间，没有意义的，能成功很快就成功了，不能成功时间再久也没有用。mTotalRepeatTime增加了。一般来说，两次就够了，安全起见，我设置为3次。

**Comment by philong9192** [comment]
> 抱歉，这段时间没有上gtihub,没有看到。因为修改是在公司的项目中进行的，不方便贴源代码。我只能给出修改思路。对比iPhone，我跟踪Android APP发现两个问题:1.guide code和data code经常没有完整发送完，这个有很大概率会导致发送配网数据失败，修改__execute函数主要是解决这个问题；2.在__listenAsyn函数里，超时收到反馈时，是忽略结果的，这个要改掉，Android手机的硬件差异导致，很多手机上必然会存在接收超时。另外，mWaitUdpReceivingMilliseond和mWaitUdpSendingMillisecond我都调小了，设置那么长时间，没有意义的，能成功很快就成功了，不能成功时间再久也没有用。mTotalRepeatTime增加了。一般来说，两次就够了，安全起见，我设置为3次。

hi Tingdang,

Thank you for your reply my comment. But I can't resolve my problem. Can you show me the source code of "__execute" function? 

Hope you help me.

**Comment by fuhaodev** [comment]
能否提个PR修复一下
