### ISSUE TITLE
Class file has wrong version 55.0, should be 52.0

### ISSUE THREAD

**Issue by Tejaswini0215** [EspressifApp/EsptouchForAndroid#78]
error: cannot access EspProvisioner
import com.espressif.iot.esptouch2.provision.EspProvisioner;
                                            ^
  bad class file: C:\Users\Admin\.gradle\caches\transforms-2\files-2.1\2b16cc810abf1f5f9f1b3e1c3bd351ed\jetified-lib-esptouch-v2-android-2.1.0-api.jar(com/espressif/iot/esptouch2/provision/EspProvisioner.class)
    class file has wrong version 55.0, should be 52.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.

**Comment by XuXiangJun** [comment]
We have modified the project and libs compatibility to Java8
Please update the lib to 2.2.0
