### ISSUE TITLE
请问下配网时发送参数TargetHostName的区别

### ISSUE THREAD

**Issue by hcw2175** [EspressifApp/EsptouchForAndroid#8]
记得以前旧的版本中在`EsptouchTaskParameter`中有个参数`mTargetHostname=255.255.255.255`，现在看到修改成了如下代码：

```java
// target hostname is : 234.1.1.1, 234.2.2.2, 234.3.3.3 to 234.100.100.100
@Override
public String getTargetHostname() {
	int count = __getNextDatagramCount();
	return "234." + count + "." + count + "." + count;
}
```

-----------
想问以下2个问题：

1. 这个TargetHost为什么修改了？
2. 我照现在的代码升级了APP，以前旧的芯片配网配不了，必须修改回"255.255.255.255"才可以，而且配网速度极慢，基本在39~45秒之间。请问如何处理此问题？

**Comment by afunx** [comment]
你好，我已经从乐鑫离职2个月了。处于职业道德，尽量简要回答一下你的问题：

1. 这个是Device那边改了协议之后改的。具体什么时候该的，你可以通过git log -p xxx.file查看文件修改记录。
2. 新老协议是不兼容的，但如果没出货的话，建议你们尽量使用新协议。配网速度极慢，这个描述太抽象了。你需要把更详细的信息，提供的乐鑫的官网或论坛。或者在github开一个issue，等待相关开发人员协助你解决。

**Comment by hcw2175** [comment]
好的，thanks
