### ISSUE TITLE
使用V2版本的aesKey加密配网的疑问?

### ISSUE THREAD

**Issue by wnylei** [EspressifApp/EsptouchForAndroid#90]
我在设备中配置如下(使用V2版本的KEY加密传输 配网):
esp_touch_v2_enable_crypt = true
esp_touch_v2_key = "wn123456wn123456"

当我使用官方的 手机端配网APP 进行配网(选择了 ESP-TOUCH-V2 版本进行配网.)

测试AES秘钥,进行配网时, 发现了下面的两种情况.
1,AES秘钥输入正确,可以配网成功. 2AES秘钥输入错误.比如"abcdefgabcdefg",配网失败. (这种情况是合理的)
2,AES秘钥输入空, 也可以配网成功. (有一个疑问如下:)
  为什么我在设备上配置了KEY秘钥. 手机端输入空的秘钥,也能配置成功呢?

**Comment by XuXiangJun** [comment]
数据包里包含是否加密的标识位
当手机端没有输入 KEY 时，发送的数据包的加密位就为非，因此设备同样能正确解析数据。

**Comment by wnylei** [comment]
了解 .  多谢
